"""add is_delete

Revision ID: 0dcb877a429c
Revises: b80c18025e4a
Create Date: 2018-09-07 14:37:51.523266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcb877a429c'
down_revision = 'b80c18025e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_category', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('menu_food', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('merchant_shop', sa.Column('is_delete', sa.Boolean(), nullable=True))
    op.add_column('merchant_user', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_user', 'is_delete')
    op.drop_column('merchant_shop', 'is_delete')
    op.drop_column('menu_food', 'is_delete')
    op.drop_column('menu_category', 'is_delete')
    # ### end Alembic commands ###
