"""init MerchantShop

Revision ID: 1cd9e5de4e38
Revises: 8e82f1e94a25
Create Date: 2018-09-05 10:46:42.434326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd9e5de4e38'
down_revision = '8e82f1e94a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_id', sa.String(length=16), nullable=True),
    sa.Column('shop_name', sa.String(length=32), nullable=False),
    sa.Column('shop_img', sa.String(length=128), nullable=True),
    sa.Column('shop_rating', sa.Float(), nullable=True),
    sa.Column('brand', sa.Boolean(), nullable=True),
    sa.Column('on_time', sa.Boolean(), nullable=True),
    sa.Column('fengniao', sa.Boolean(), nullable=True),
    sa.Column('bao', sa.Boolean(), nullable=True),
    sa.Column('piao', sa.Boolean(), nullable=True),
    sa.Column('zhun', sa.Boolean(), nullable=True),
    sa.Column('start_send', sa.Float(), nullable=True),
    sa.Column('send_cost', sa.Float(), nullable=True),
    sa.Column('notice', sa.String(length=210), nullable=True),
    sa.Column('discount', sa.String(length=210), nullable=True),
    sa.Column('merchant_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_uid'], ['merchant_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_name')
    )
    op.create_index(op.f('ix_merchant_shop_pub_id'), 'merchant_shop', ['pub_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_shop_pub_id'), table_name='merchant_shop')
    op.drop_table('merchant_shop')
    # ### end Alembic commands ###
