"""init mun

Revision ID: b80c18025e4a
Revises: 1cd9e5de4e38
Create Date: 2018-09-05 17:04:23.145892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80c18025e4a'
down_revision = '1cd9e5de4e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('type_accumulation', sa.String(length=16), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['merchant_shop.pub_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.String(length=8), nullable=True),
    sa.Column('goods_name', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('goods_price', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('month_sales', sa.Integer(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('tips', sa.String(length=128), nullable=True),
    sa.Column('goods_img', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['menu_category.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['merchant_shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_food')
    op.drop_table('menu_category')
    # ### end Alembic commands ###
